---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-logs-agent
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: b3fb668c-6f9d-4db3-9073-9a677ccf4394
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validation-deploy-slz-roks-and-obs-instances.sh"
        post_validation: "tests/scripts/post-validation-destroy-slz-roks-and-obs-instances.sh"
